services:
  # Development version with volume mounting
  app-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: next-map-app-dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://${POSTGRES_USER:-nextmap}:${POSTGRES_PASSWORD:-nextmap_password}@postgres:5432/${POSTGRES_DB:-nextmap}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_MAP_API_KEY: ${NEXT_PUBLIC_MAP_API_KEY}
      WATCHPACK_POLLING: true
    ports:
      - '${APP_DEV_PORT:-3001}:3000'
    volumes:
      # Mount your local source code
      - ..:/app
      - /app/node_modules
      - /app/.next
    networks:
      - next-map-network
    depends_on:
      postgres:
        condition: service_healthy

networks:
  next-map-network:
    external: true
